export const PRODUCT_GROUP_LIST_REQUEST = 'PRODUCT_GROUP_LIST_REQUEST'
export const PRODUCT_GROUP_LIST_SUCCESS = 'PRODUCT_GROUP_LIST_SUCCESS'
export const PRODUCT_GROUP_LIST_FAIL = 'PRODUCT_GROUP_LIST_FAIL'
